FROM mcr.microsoft.com/dotnet/core/sdk:3.0 AS build
WORKDIR /src

COPY RobotCleaner.csproj .

RUN dotnet restore

COPY . .

RUN dotnet publish -r linux-x64 -c release -o /app

FROM microsoft/aspnetcore:latest
WORKDIR /app

COPY --from=build /app .

ENTRYPOINT ["dotnet", "RobotCleaner.dll"]